### ISSUE TITLE
Questions to ask Tunde and Rodney / Creating Forms and Front End site 

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [Unitie-FAC/Unitie-MVP#10]
What is the full list of input fields for societies and companies? 
Where is unitie.co.uk hosted? 
Heroku payment details, set up with Tunde/Rodney.

**Comment by tormod17** [comment]
We also need the web content , e.g. text, photo's, logo.

**Comment by sohilpandya** [comment]
- themes or from scratch?
- walk through github issues. 
- filters for searching database? 
- signature on contract and company name and email for invoice

**Comment by tormod17** [comment]
A suggested theme https://w3layouts.com/preview/?l=/vivamus-corporate-portfolio-flat-bootstrap-responsive-web-template/

**Comment by Joshua-Ronan-Phillips** [comment]
list of inputs.

Society name - text  MAND
University - autofil/dropdown/other MAND
Specify other MAND
Region - Dropdown List MAND
Member size - Dropdown ranges MAND
Email -  text MAND
Phone - uk validated
About us - text 
Logo - upload image

COMPANIES
ComPany name - text MAND
Industry - dropdown MAND
Contact name -text MAND
Email - MAND
Phone Number
Target Region - Checkboxes MAND
Please tell us types of societies - Checkboxes MAND 

Hidden inputs: Timestamp, ID number.

Filter : Societies, Region, University, Type of society, Member size.
           Companies, industry, type of society interested in, target region.

**Comment by officialunitie** [comment]
Company Name 
Industry Sector - http://www.lse.co.uk/uk-sectors.asp ( add Other to list)
Contact Name
Email
Contact Number
Target Region(s) - https://uk.freecycle.org/regions ( add Nationwide to list)
Student Societies Interested in Partnering with (Please refer to society type here https://docs.google.com/forms/d/1m6vinN9v39DzfHG5ZQRGrDMMXJY_dQPqGxgRY_F2D04/viewform?c=0&w=1) 

Society Name
University Name - https://www.gov.uk/check-a-university-is-officially-recognised/recognised-bodies Region - https://uk.freecycle.org/regions
Society Member Size - (Please refer to member size drop down on - https://docs.google.com/forms/d/1m6vinN9v39DzfHG5ZQRGrDMMXJY_dQPqGxgRY_F2D04/viewform?c=0&w=1)
Society Email 
Phone Number
Tell us a bit about your Society 
Society Logo

**Comment by sohilpandya** [comment]
@officialunitie are we scrapping the type of society drop down that we had in the society section? 

as its not present in the above comment. please let us know. 

Thanks

**Comment by officialunitie** [comment]
@sohilpandya apologies we're not scrapping in. Please include as 'Society Type'

**Comment by sohilpandya** [comment]
@officialunitie great. will keep it in, please forward the items that will go in the society type dropdown.

**Comment by officialunitie** [comment]
@sohilpandya  (Please refer to society type here https://docs.google.com/forms/d/1m6vinN9v39DzfHG5ZQRGrDMMXJY_dQPqGxgRY_F2D04/viewform?c=0&w=1)

**Comment by sohilpandya** [comment]
Thanks.

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie the image Tunde last night via whats app photo looked like the work you did with the designer. If so, could you send us those files as that would be massively beneficial at this stage. What's the status with the layout and styling of the website? Tunde sent us the very basic version but we'll need something much more detailed asap too.

**Comment by officialunitie** [comment]
@Joshua-Ronan-Phillips  the layout is as in the photos i sent you. The designer is still working on various icons etc. We'll set up a g drive and share everything through there.

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie that's great, me and Tormod have discussed and there are still things that we will need that are holding us back in terms of making it look how you want. 

In priority order they are: 
- Images you currently have and if you don't have some images then find the rest and send them over.
- Logo's and icons (if you need help on this you can send an image or description of icons you need and we can find some but it would save time if you picked them because we might not find ones you like and it will take longer)
- Example of the type of form you want (we have the form inputs skeleton already but need this to start styling)
-  Content for the text that will go in each section

The reason I say this is holding us back on continuing with the layout/styling of the website is the code will be heavily dependant on the images/logos/icons you provide. If we started now, we would double up the work when you eventually send them over as they will effect everything else on the page.

For now we are working on a number of technical issues but we are keen to move forward with the look of the website asap as we know from experience this takes a significant amount of time and will be subject to revisions to get it looking exactly as you want it.

If you have any files now, please send those over. Quick question, are the sections, 'case studies' and 'services' for the companies page only?

If you need to confirm anything via phone please feel free to contact me.

Best

Josh

**Comment by officialunitie** [comment]
Yes case studies and services is only for brands. 

We'll send the all the images, video and icon to you in the next 2 hours. We'll share a g drive with you and label the stuff accordingly.

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie that's great news guys

**Comment by tormod17** [comment]
@officialunitie https://drive.google.com/drive/folders/0B8fFTHZBnspMN0lpMEdkRV9SQVU

the Unitie Services icons are all on one image the separated images have no images. If it's difficult to get the icons point us to the library where you are downloading the images.

**Comment by officialunitie** [comment]
@tormod17 The Unitie separated services icons are all there, although their colour have been formatted white.  and so difficult to see.

**Comment by officialunitie** [comment]
@Joshua-Ronan-Phillips @thegsi @tormod17 @sohilpandya  the video for the homepage is in the g drive in the video folder

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie many thanks

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie here is the link to the site: http://young-caverns-8279.herokuapp.com/ 
The database is connected and completed.
We have a dashboard on our local version too but there's some errors on that.

As for the front end website you can play around with it's obviously no where near ready yet, this is the basic info, pics layout with some of the fuctionality, (working nav-bar, autocomplete for universities, ect.)

We have spent more time on the back-end this week and will spend a lot more on the front end next week as we are starting to have a better idea of what you want, feedback at this stage is still encouraged even in this rough and ready state. If there are things about layout that are changing from Tunde's original basic sketches now that you can see the rough structure then tell us asap.

**Comment by officialunitie** [comment]
@Joshua-Ronan-Phillips @sohilpandya @tormod17 @thegsi website content has been uploaded in the g drive in the website content folder, please refer to layout pics, fanbytes website and also use intuition for relative sizes of texts, all info is in the doc

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie thanks we saw it this morning and have been working on some of it.

**Comment by Joshua-Ronan-Phillips** [comment]
@officialunitie there is no white clock icon only black. We tried to edit this but with not much luck as photoshop is not in our current skill set. For now we are using the white clock, if you want the tie please can you get the designer to modify
