### ISSUE TITLE
Add automated email -using mandrill 

### ISSUE THREAD

**Issue by tormod17** [Unitie-FAC/Unitie-MVP#155]

**Comment by thegsi** [comment]
Waiting on email copy from Tunde and Rodney

**Comment by officialunitie** [comment]
cool, we're working on it today.

**Comment by officialunitie** [comment]
Hi, Ive sent you via the email the content for the automated emails. Couldn't put it on the g drive for some reason. 

Within the both emails, could you kindly replace the 'Hi...' with 'Hi..**'then the recipients name'.**..'

Thanks

@tormod17 @thegsi @sohilpandya @Joshua-Ronan-Phillips

**Comment by thegsi** [comment]
@officialunitie  Just adding the email content now, the email looks great! One issues, you have preferences/unsubscribe at the bottom. However users have not subscribed to anything. Should I remove?

**Comment by officialunitie** [comment]
@thegsi yes please remove preferences/unsubscribe

**Comment by officialunitie** [comment]
hi, just tried the email service, and it works great! Thanks!

One amendment. for the subject of the email, could you also include an additional exclamation mark after 'Welcome to Unitie' for both emails. - thanks

@thegsi @tormod17

**Comment by officialunitie** [comment]
also my bad, theres a typo in the brand email. 

The last bit of text within the brand email should read:

'In the meantime, if you have any questions or if you would like us to assist you in a campaign targeted towards the student demographic, just drop us an email!'

once again MY APOLOGIES 

@tormod17 @thegsi
