### ISSUE TITLE
Testing video on safari 

### ISSUE THREAD

**Issue by tormod17** [Unitie-FAC/Unitie-MVP#156]
http://stackoverflow.com/questions/2643447/html5-video-mp4-and-ogv-problems-in-safari-and-firefox-but-chrome-is-all-goo?rq=1

**Comment by thegsi** [comment]
.htaccess file

**Comment by tormod17** [comment]
this was tutorial we used http://thenewcode.com/777/Create-Fullscreen-HTML5-Page-Background-Video

**Comment by officialunitie** [comment]
wasnt working on my safari
