### ISSUE TITLE
Video Filter

### ISSUE THREAD

**Issue by officialunitie** [Unitie-FAC/Unitie-MVP#194]
Two more videos have been uploaded in the g drive within the video folder. 
One titled 'light', the other titled 'dark'.

For now could you put on the 'dark' one. Then will review to see how it looks. Just email us when this is done and we'll have a look.

**Comment by thegsi** [comment]
@officialunitie the dark video is now available for viewing.

**Comment by officialunitie** [comment]
cool, we like the video that is up now.
