### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by officialunitie** [Unitie-FAC/Unitie-MVP#195]
will provide you with them later today

**Comment by officialunitie** [comment]
facebook - https://www.facebook.com/officialunitie
twitter - https://twitter.com/officialunitie
linkedin - https://www.linkedin.com/company/6408057?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A6408057%2Cidx%3A3-1-3%2CtarId%3A1454000546826%2Ctas%3Aunitie

@thegsi @tormod17 @sohilpandya @Joshua-Ronan-Phillips

**Comment by officialunitie** [comment]
also could we just have the logos as the links to our social media pages, opposed to it actually saying facebook, twitter etc. 
Also not sure, how far into you are, but social media links on student doesn't appear to be working 

@thegsi @tormod17 @sohilpandya @Joshua-Ronan-Phillips

**Comment by tormod17** [comment]
this has been fixed.
