### ISSUE TITLE
opening video on safari doesnt work, comes out as a still image

### ISSUE THREAD

**Issue by officialunitie** [Unitie-FAC/Unitie-MVP#211]
@tormod17 @thegsi

**Comment by tormod17** [comment]
@officialunitie on multiple safari browsers this is now working.

**Comment by officialunitie** [comment]
@tormod17 @thegsi still doesnt work on my version of safari. Please could you make the necessary arrangement to ensure it is working on all browser and versions. Important as many students will have previous versions of browsers

**Comment by thegsi** [comment]
@officialunitie  We have just made some changes. Should work now.

**Comment by officialunitie** [comment]
Yep it does
