### ISSUE TITLE
unitie.co.uk does not work on both computer or mobile browsers. (www.unitie.co.uk does work).

### ISSUE THREAD

**Issue by officialunitie** [Unitie-FAC/Unitie-MVP#222]

**Comment by officialunitie** [comment]
unitie.co.uk on Web-browser Safari works, but not on google Chrome.

**Comment by officialunitie** [comment]
@tormod17 @thegsi

**Comment by tormod17** [comment]
@officialunitie guys can we have the details for 123 reg?  This is where you bought your domain name from. At the moment you have a 100gb hosting service from Go Daddy but are not actually using this as the site is hosted on Heroku, to get Redis hosted on Godaddy you would need to increase your package to £50 amonth.  Hopefully we can skip out Godaddy and go straight from 123 reg to Heroku. I spoke with Godaddy and there might be a chance you can cancel your service and get a refund. If you get me the details I'll set it up today.

**Comment by officialunitie** [comment]
Username: rodney.a.johnson@hotmail.com

**Comment by officialunitie** [comment]
Pass: fandcoders123

**Comment by tormod17** [comment]
@officialunitie okay both www.unitie.co.uk and unitie.co.uk are forwarding to young-caverns I have change the DNS details on 123 reg it can take upto 48 hours to point properly.  With regards to Go Daddy you are not using their services for anything so I would give them a call and tell them so.

**Comment by officialunitie** [comment]
@tormod17 @thegsi ok, currently both www.unitie.co.uk, unitie.co.uk go to young-caverns website, as in doesn't say www.unitie.co.uk in the browser.

**Comment by tormod17** [comment]
this has now been addressed.

**Comment by officialunitie** [comment]
unitie.co.uk currently redirects to http://young-caverns-8279.herokuapp.com/

**Comment by tormod17** [comment]
check that you have cleared browsing history  unitie.co.uk is pointint to www.unitie.co.uk

**Comment by officialunitie** [comment]
My apologies, its running fine
