### ISSUE TITLE
www.unitie.co.uk/admin doesnt work

### ISSUE THREAD

**Issue by officialunitie** [Unitie-FAC/Unitie-MVP#225]
@tormod17 @thegsi  comes up with '{"statusCode":404,"error":"Not Found"}'

**Comment by tormod17** [comment]
@officialunitie hmmm - I'm still trying to permanently fix the root domain if you could just make sure that you have '/' before admin when it redirects you will be able to access the admin page. 
http://young-caverns-8279.herokuapp.com/admin
