### ISSUE TITLE
Adding HTML , Bootstrap Skeleton to Societies/Companies HMTL page. #1#10

### ISSUE THREAD

**Issue by tormod17** [Unitie-FAC/Unitie-MVP#26]

**Comment by tormod17** [comment]
Added endpoints but on submission return 404 . Added Skeleton html and bootstrap CSS

**Comment by Joshua-Ronan-Phillips** [comment]
@tormod17 so I don't forget, on the society page the top right register button doesn't take us to the section

**Comment by Joshua-Ronan-Phillips** [comment]
I've changed the id in the society form to companyRegister for now, we can chat if there is a better way

**Comment by Joshua-Ronan-Phillips** [comment]
@tormod17  We've also got an issue that the navbar when on a smaller device will not collapse the menu when you've made a choice and doesn't adjust to different view-ports/devices.

**Comment by tormod17** [comment]
@Joshua-Ronan-Phillips  yeah i think we need to sort the links out as when we updated it with handlebars some of the sections changed.

**Comment by Joshua-Ronan-Phillips** [comment]
skeleton done.
