### ISSUE TITLE
Autocomplete function for universities - adding to form #10

### ISSUE THREAD

**Issue by tormod17** [Unitie-FAC/Unitie-MVP#29]

**Comment by tormod17** [comment]
https://files.gitter.im/codingforeveryone/Unitie/qcBF/Unitie-university-list.csv  list of Universities and Cities universities are located in.

**Comment by Joshua-Ronan-Phillips** [comment]
@Joshua-Ronan-Phillips

**Comment by tormod17** [comment]
https://github.com/fcscripters/tuber/blob/master/js/autocomplete.js  previous project using auto-complete.

**Comment by Joshua-Ronan-Phillips** [comment]
dropdown with search = http://blog.teamtreehouse.com/creating-autocomplete-dropdowns-datalist-element. However its not supported by safari, some older browsers dont support it either.

**Comment by tormod17** [comment]
Need conditional to sort out 'of' in title case

**Comment by sohilpandya** [comment]
@tormod17  @Joshua-Ronan-Phillips also at the moment, when I type in southampton it returns southampton solent university, surely it should return all universities that have the world southampton in it?

**Comment by tormod17** [comment]
@sohilpandya the auto-complete matches the string it doesn't search the string this is a further feature that we can add but at the moment I think we should sort the 'title case ' issue first.

**Comment by tormod17** [comment]
changed so title case fixes first word only , but remaining words user will have to match list provided by auto-complete . This allows user to match list.

**Comment by Joshua-Ronan-Phillips** [comment]
done
