### ISSUE TITLE
Adding video to background of home page. (research best practice for loading speed) #1

### ISSUE THREAD

**Issue by tormod17** [Unitie-FAC/Unitie-MVP#32]

**Comment by tormod17** [comment]
http://thenewcode.com/777/Create-Fullscreen-HTML5-Page-Background-Video  interesting

**Comment by sohilpandya** [comment]
Liking it boys, great video on at the moment. works perfectly on mobile and web. just one thing, mobile photo doesn't cover the whole page. sure you noticed it too! :)

**Comment by Joshua-Ronan-Phillips** [comment]
done
