### ISSUE TITLE
Contact Us section 

### ISSUE THREAD

**Issue by tormod17** [Unitie-FAC/Unitie-MVP#69]
@officialunitie  Need relevant contact details to enter into site.

**Comment by officialunitie** [comment]
@tormod17 info@unitie.co.uk

**Comment by officialunitie** [comment]
@tormod17 anyway it could be similar to this https://fanbytes.co.uk/contact-us/

**Comment by officialunitie** [comment]
@tormod17 a seperate page

**Comment by tormod17** [comment]
@officialunitie  rather than create another form page we can have a section that links to phone and mail client on click. This is more user friendly as it allows users to use the full ablity of mail client (out look) to communicate with you rather than restricting to form.  Looks somehting like this 
![image](https://cloud.githubusercontent.com/assets/11330267/12244050/19945710-b878-11e5-8b26-a9cfc143a417.png)

**Comment by officialunitie** [comment]
@tormod17 sweet, love the initiative!

**Comment by tormod17** [comment]
@officialunitie guys was thinking on the home page in the top right corner we have the Contact Us link. This could drop down with contact details, another option would be to just display your contact details directly below the 'I AM  A STUDENT'  and 'I AM A BRAND' buttons.

**Comment by officialunitie** [comment]
@tormod17 drop down sounds good. Also can you make the homepage similar to the fanbytes home page please. So no banner and our logo isn't there. Just UNITIE in bold top lift and thicker text, and other relative text formatting. Thanks. Also can you ensure an underline does not come up under 'i am a brand, i am a student' when the mouse hovers over it, but it is still hightlighted.

**Comment by tormod17** [comment]
@officialunitie  sure I can do that no problem I had changed this however in accordance to the previous instruction 'first line': 

_"Content for homepage:_ 

_[Add a banner to the top, similar to www.unitie.co.uk, separating video from where the logo is]_

‘UNITIE’ – bold, positioning: top left 
‘Connecting Student Societies and Brands’ - positioning: centered in middle of page
‘I AM A BRAND’ - bold, positioning: below above text,  button on the left
‘I AM A STUDENT’ - bold, positioning: below above text, button on the right
‘Contact us’ – top right*
